/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationResetPasswordPostRequest
 */
export interface AuthenticationResetPasswordPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResetPasswordPostRequest
     */
    username: string;
}

/**
 * Check if a given object implements the AuthenticationResetPasswordPostRequest interface.
 */
export function instanceOfAuthenticationResetPasswordPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function AuthenticationResetPasswordPostRequestFromJSON(json: any): AuthenticationResetPasswordPostRequest {
    return AuthenticationResetPasswordPostRequestFromJSONTyped(json, false);
}

export function AuthenticationResetPasswordPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationResetPasswordPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function AuthenticationResetPasswordPostRequestToJSON(value?: AuthenticationResetPasswordPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
    };
}

