/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationEmailPostRequest
 */
export interface AuthenticationEmailPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailPostRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailPostRequest
     */
    confirmPassword: string;
}

/**
 * Check if a given object implements the AuthenticationEmailPostRequest interface.
 */
export function instanceOfAuthenticationEmailPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "confirmPassword" in value;

    return isInstance;
}

export function AuthenticationEmailPostRequestFromJSON(json: any): AuthenticationEmailPostRequest {
    return AuthenticationEmailPostRequestFromJSONTyped(json, false);
}

export function AuthenticationEmailPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationEmailPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
    };
}

export function AuthenticationEmailPostRequestToJSON(value?: AuthenticationEmailPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'confirmPassword': value.confirmPassword,
    };
}

