/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationResetPasswordPutRequest
 */
export interface AuthenticationResetPasswordPutRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResetPasswordPutRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResetPasswordPutRequest
     */
    passwordRecoveryKey: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResetPasswordPutRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResetPasswordPutRequest
     */
    confirmPassword: string;
}

/**
 * Check if a given object implements the AuthenticationResetPasswordPutRequest interface.
 */
export function instanceOfAuthenticationResetPasswordPutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "passwordRecoveryKey" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "confirmPassword" in value;

    return isInstance;
}

export function AuthenticationResetPasswordPutRequestFromJSON(json: any): AuthenticationResetPasswordPutRequest {
    return AuthenticationResetPasswordPutRequestFromJSONTyped(json, false);
}

export function AuthenticationResetPasswordPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationResetPasswordPutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'passwordRecoveryKey': json['passwordRecoveryKey'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
    };
}

export function AuthenticationResetPasswordPutRequestToJSON(value?: AuthenticationResetPasswordPutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'passwordRecoveryKey': value.passwordRecoveryKey,
        'password': value.password,
        'confirmPassword': value.confirmPassword,
    };
}

