/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface AuthenticationPostDefaultResponse
 */
export interface AuthenticationPostDefaultResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationPostDefaultResponse
     */
    token?: string;
    /**
     * 
     * @type {User}
     * @memberof AuthenticationPostDefaultResponse
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationPostDefaultResponse
     */
    authenticationId?: string;
}

/**
 * Check if a given object implements the AuthenticationPostDefaultResponse interface.
 */
export function instanceOfAuthenticationPostDefaultResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthenticationPostDefaultResponseFromJSON(json: any): AuthenticationPostDefaultResponse {
    return AuthenticationPostDefaultResponseFromJSONTyped(json, false);
}

export function AuthenticationPostDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationPostDefaultResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'authenticationId': !exists(json, 'authenticationId') ? undefined : json['authenticationId'],
    };
}

export function AuthenticationPostDefaultResponseToJSON(value?: AuthenticationPostDefaultResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'user': UserToJSON(value.user),
        'authenticationId': value.authenticationId,
    };
}

