/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationGooglePostRequest
 */
export interface AuthenticationGooglePostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationGooglePostRequest
     */
    token: string;
}

/**
 * Check if a given object implements the AuthenticationGooglePostRequest interface.
 */
export function instanceOfAuthenticationGooglePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function AuthenticationGooglePostRequestFromJSON(json: any): AuthenticationGooglePostRequest {
    return AuthenticationGooglePostRequestFromJSONTyped(json, false);
}

export function AuthenticationGooglePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationGooglePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function AuthenticationGooglePostRequestToJSON(value?: AuthenticationGooglePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

