/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationApplePostRequest
 */
export interface AuthenticationApplePostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationApplePostRequest
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationApplePostRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationApplePostRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationApplePostRequest
     */
    place?: string;
}

/**
 * Check if a given object implements the AuthenticationApplePostRequest interface.
 */
export function instanceOfAuthenticationApplePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;

    return isInstance;
}

export function AuthenticationApplePostRequestFromJSON(json: any): AuthenticationApplePostRequest {
    return AuthenticationApplePostRequestFromJSONTyped(json, false);
}

export function AuthenticationApplePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationApplePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'place': !exists(json, 'place') ? undefined : json['place'],
    };
}

export function AuthenticationApplePostRequestToJSON(value?: AuthenticationApplePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'place': value.place,
    };
}

