/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationPutRequest
 */
export interface AuthenticationPutRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationPutRequest
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationPutRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationPutRequest
     */
    confirmNewPassword: string;
}

/**
 * Check if a given object implements the AuthenticationPutRequest interface.
 */
export function instanceOfAuthenticationPutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "currentPassword" in value;
    isInstance = isInstance && "newPassword" in value;
    isInstance = isInstance && "confirmNewPassword" in value;

    return isInstance;
}

export function AuthenticationPutRequestFromJSON(json: any): AuthenticationPutRequest {
    return AuthenticationPutRequestFromJSONTyped(json, false);
}

export function AuthenticationPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationPutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
        'confirmNewPassword': json['confirmNewPassword'],
    };
}

export function AuthenticationPutRequestToJSON(value?: AuthenticationPutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentPassword': value.currentPassword,
        'newPassword': value.newPassword,
        'confirmNewPassword': value.confirmNewPassword,
    };
}

