/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationEmailPutRequest
 */
export interface AuthenticationEmailPutRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailPutRequest
     */
    emailVerificationKey: string;
}

/**
 * Check if a given object implements the AuthenticationEmailPutRequest interface.
 */
export function instanceOfAuthenticationEmailPutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "emailVerificationKey" in value;

    return isInstance;
}

export function AuthenticationEmailPutRequestFromJSON(json: any): AuthenticationEmailPutRequest {
    return AuthenticationEmailPutRequestFromJSONTyped(json, false);
}

export function AuthenticationEmailPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationEmailPutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailVerificationKey': json['emailVerificationKey'],
    };
}

export function AuthenticationEmailPutRequestToJSON(value?: AuthenticationEmailPutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailVerificationKey': value.emailVerificationKey,
    };
}

