/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoritePostRequest
 */
export interface FavoritePostRequest {
    /**
     * 
     * @type {string}
     * @memberof FavoritePostRequest
     */
    rentableId: string;
}

/**
 * Check if a given object implements the FavoritePostRequest interface.
 */
export function instanceOfFavoritePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rentableId" in value;

    return isInstance;
}

export function FavoritePostRequestFromJSON(json: any): FavoritePostRequest {
    return FavoritePostRequestFromJSONTyped(json, false);
}

export function FavoritePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rentableId': json['rentableId'],
    };
}

export function FavoritePostRequestToJSON(value?: FavoritePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rentableId': value.rentableId,
    };
}

