/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RentableTypeEnum = {
    Place: 'PLACE',
    Item: 'ITEM',
    Service: 'SERVICE',
    Auto: 'AUTO'
} as const;
export type RentableTypeEnum = typeof RentableTypeEnum[keyof typeof RentableTypeEnum];


export function RentableTypeEnumFromJSON(json: any): RentableTypeEnum {
    return RentableTypeEnumFromJSONTyped(json, false);
}

export function RentableTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentableTypeEnum {
    return json as RentableTypeEnum;
}

export function RentableTypeEnumToJSON(value?: RentableTypeEnum | null): any {
    return value as any;
}

