/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentableGeolocation
 */
export interface RentableGeolocation {
    /**
     * 
     * @type {number}
     * @memberof RentableGeolocation
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof RentableGeolocation
     */
    y: number;
}

/**
 * Check if a given object implements the RentableGeolocation interface.
 */
export function instanceOfRentableGeolocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "x" in value;
    isInstance = isInstance && "y" in value;

    return isInstance;
}

export function RentableGeolocationFromJSON(json: any): RentableGeolocation {
    return RentableGeolocationFromJSONTyped(json, false);
}

export function RentableGeolocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentableGeolocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function RentableGeolocationToJSON(value?: RentableGeolocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
    };
}

