/* tslint:disable */
/* eslint-disable */
/**
 * LuuGo - Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthenticationEmailPostRequest,
  AuthenticationEmailPutRequest,
  AuthenticationPostDefaultResponse,
  AuthenticationPostRequest,
  AuthenticationResetPasswordPostRequest,
  AuthenticationResetPasswordPutRequest,
} from '../models/index';
import {
    AuthenticationEmailPostRequestFromJSON,
    AuthenticationEmailPostRequestToJSON,
    AuthenticationEmailPutRequestFromJSON,
    AuthenticationEmailPutRequestToJSON,
    AuthenticationPostDefaultResponseFromJSON,
    AuthenticationPostDefaultResponseToJSON,
    AuthenticationPostRequestFromJSON,
    AuthenticationPostRequestToJSON,
    AuthenticationResetPasswordPostRequestFromJSON,
    AuthenticationResetPasswordPostRequestToJSON,
    AuthenticationResetPasswordPutRequestFromJSON,
    AuthenticationResetPasswordPutRequestToJSON,
} from '../models/index';

export interface AuthenticationEmailDeleteRequest {
    authenticationEmailPostRequest: AuthenticationEmailPostRequest;
    acceptLanguage?: string;
}

export interface AuthenticationEmailPostOperationRequest {
    authenticationEmailPostRequest: AuthenticationEmailPostRequest;
    acceptLanguage?: string;
}

export interface AuthenticationEmailPutOperationRequest {
    authenticationEmailPutRequest: AuthenticationEmailPutRequest;
    acceptLanguage?: string;
}

export interface AuthenticationPostOperationRequest {
    authenticationPostRequest: AuthenticationPostRequest;
    acceptLanguage?: string;
}

export interface AuthenticationResetPasswordPostOperationRequest {
    authenticationResetPasswordPostRequest: AuthenticationResetPasswordPostRequest;
    acceptLanguage?: string;
}

export interface AuthenticationResetPasswordPutOperationRequest {
    authenticationResetPasswordPutRequest: AuthenticationResetPasswordPutRequest;
    acceptLanguage?: string;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Deletes an user by using the user authentication
     * Deletes an user by using the user authentication
     */
    async authenticationEmailDeleteRaw(requestParameters: AuthenticationEmailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authenticationEmailPostRequest === null || requestParameters.authenticationEmailPostRequest === undefined) {
            throw new runtime.RequiredError('authenticationEmailPostRequest','Required parameter requestParameters.authenticationEmailPostRequest was null or undefined when calling authenticationEmailDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        const response = await this.request({
            path: `/authentication/email`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationEmailPostRequestToJSON(requestParameters.authenticationEmailPostRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an user by using the user authentication
     * Deletes an user by using the user authentication
     */
    async authenticationEmailDelete(requestParameters: AuthenticationEmailDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authenticationEmailDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * This is the first step to register an user by email.
     * Register an authenthication
     */
    async authenticationEmailPostRaw(requestParameters: AuthenticationEmailPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authenticationEmailPostRequest === null || requestParameters.authenticationEmailPostRequest === undefined) {
            throw new runtime.RequiredError('authenticationEmailPostRequest','Required parameter requestParameters.authenticationEmailPostRequest was null or undefined when calling authenticationEmailPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        const response = await this.request({
            path: `/authentication/email`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationEmailPostRequestToJSON(requestParameters.authenticationEmailPostRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This is the first step to register an user by email.
     * Register an authenthication
     */
    async authenticationEmailPost(requestParameters: AuthenticationEmailPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authenticationEmailPostRaw(requestParameters, initOverrides);
    }

    /**
     * This is the second step to register an user by email.
     * Verify an email
     */
    async authenticationEmailPutRaw(requestParameters: AuthenticationEmailPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.authenticationEmailPutRequest === null || requestParameters.authenticationEmailPutRequest === undefined) {
            throw new runtime.RequiredError('authenticationEmailPutRequest','Required parameter requestParameters.authenticationEmailPutRequest was null or undefined when calling authenticationEmailPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        const response = await this.request({
            path: `/authentication/email`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationEmailPutRequestToJSON(requestParameters.authenticationEmailPutRequest),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This is the second step to register an user by email.
     * Verify an email
     */
    async authenticationEmailPut(requestParameters: AuthenticationEmailPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.authenticationEmailPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Given an username and password it will return the user and a token which will be used for authenticate in many other api endpoints.
     * Authenticate the user
     */
    async authenticationPostRaw(requestParameters: AuthenticationPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationPostDefaultResponse>> {
        if (requestParameters.authenticationPostRequest === null || requestParameters.authenticationPostRequest === undefined) {
            throw new runtime.RequiredError('authenticationPostRequest','Required parameter requestParameters.authenticationPostRequest was null or undefined when calling authenticationPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        const response = await this.request({
            path: `/authentication`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationPostRequestToJSON(requestParameters.authenticationPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationPostDefaultResponseFromJSON(jsonValue));
    }

    /**
     * Given an username and password it will return the user and a token which will be used for authenticate in many other api endpoints.
     * Authenticate the user
     */
    async authenticationPost(requestParameters: AuthenticationPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationPostDefaultResponse> {
        const response = await this.authenticationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This is the first step to reset the user password.
     * Create the reset password token and send it by email to the user
     */
    async authenticationResetPasswordPostRaw(requestParameters: AuthenticationResetPasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authenticationResetPasswordPostRequest === null || requestParameters.authenticationResetPasswordPostRequest === undefined) {
            throw new runtime.RequiredError('authenticationResetPasswordPostRequest','Required parameter requestParameters.authenticationResetPasswordPostRequest was null or undefined when calling authenticationResetPasswordPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        const response = await this.request({
            path: `/authentication/resetPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationResetPasswordPostRequestToJSON(requestParameters.authenticationResetPasswordPostRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This is the first step to reset the user password.
     * Create the reset password token and send it by email to the user
     */
    async authenticationResetPasswordPost(requestParameters: AuthenticationResetPasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authenticationResetPasswordPostRaw(requestParameters, initOverrides);
    }

    /**
     * This is the second and final step to recovery the user password.
     * Reset the user password
     */
    async authenticationResetPasswordPutRaw(requestParameters: AuthenticationResetPasswordPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.authenticationResetPasswordPutRequest === null || requestParameters.authenticationResetPasswordPutRequest === undefined) {
            throw new runtime.RequiredError('authenticationResetPasswordPutRequest','Required parameter requestParameters.authenticationResetPasswordPutRequest was null or undefined when calling authenticationResetPasswordPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        const response = await this.request({
            path: `/authentication/resetPassword`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationResetPasswordPutRequestToJSON(requestParameters.authenticationResetPasswordPutRequest),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This is the second and final step to recovery the user password.
     * Reset the user password
     */
    async authenticationResetPasswordPut(requestParameters: AuthenticationResetPasswordPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.authenticationResetPasswordPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
