name: Prevent Direct Pushes to Main (Except Admins)

on:
  push:
    branches:
      - main

jobs:
  block-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check User Permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          USER_LOGIN=$(jq -r ".pusher.name" "$GITHUB_EVENT_PATH")
          REPO_FULL_NAME="${{ github.repository }}"

          # Fetch user permissions from GitHub API
          USER_ROLE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO_FULL_NAME/collaborators/$USER_LOGIN/permission" \
              | jq -r '.permission')

          # Admins and maintainers are allowed to push
          if [[ "$USER_ROLE" == "admin" ]] || [[ "$USER_ROLE" == "maintain" ]]; then
              echo "✅ User $USER_LOGIN is an admin/maintainer. Push allowed."
              exit 0
          fi

          # Block the push for other users
          echo "❌ User $USER_LOGIN does not have admin privileges. Direct pushes to main are not allowed."
          exit 1
