name: Prevent Direct Pushes to Main (Except Admins)

on:
  push:
    branches:
      - main

jobs:
  block-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check User Permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          USER_LOGIN=$(jq -r ".pusher.name" "$GITHUB_EVENT_PATH")
          REPO_FULL_NAME="${{ github.repository }}"

          # Fetch user permissions from GitHub API
          USER_ROLE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO_FULL_NAME/collaborators/$USER_LOGIN/permission" \
              | jq -r '.permission')

          # Allow admins/maintainers to push
          if [[ "$USER_ROLE" == "admin" ]] || [[ "$USER_ROLE" == "maintain" ]]; then
              echo "✅ User $USER_LOGIN is an admin/maintainer. Push allowed."
              exit 0
          fi

          echo "❌ User $USER_LOGIN does not have admin privileges. Reverting their commit."

          # Revert the commit
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git fetch origin main
          git reset --hard origin/main^
          git push --force origin main

          exit 1
